### ISSUE TITLE
Text doesn't show

### ISSUE THREAD

**Issue by xumical** [ridoy/pokemon-showdown-god-mode#1]
Hi, I installed this, joined a gen7 random battle game, but the text area is just blank. No moves, or how much damage, etc.

**Comment by ridoy** [comment]
Just pushed a new change, please download that, refresh the extension in `chrome://extensions`, and try again. 

If the problem persists let me know. A screenshot would be helpful.

**Comment by xumical** [comment]
> Just pushed [this change which should fix the issue](https://github.com/ridoy/pokemon-showdown-god-mode/commit/ed49567a07f9c8e2cb7f78030b2bf9621042b57c), please download that (or just the latest changes at the time you read this), refresh the extension in `chrome://extensions`, and try again.
> 
> Please let me know if that fixes the issue. If not, a screenshot would be helpful.

Hi! sorry for the late reply, the update you pushed fixed the issue for me.

**Comment by ridoy** [comment]
Awesome, hope you enjoy using it. Compatibility with more battle formats soon. Closing issue
